name: Remove label

on:
  pull_request_review:
    types: [submitted]

jobs:
  full-context:
    runs-on: ubuntu-latest
    steps:
      - name: Full Context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"

  remove-label:
    runs-on: ubuntu-latest
    if: |
      (github.event.pull_request.user.login == 'BoweiZhang-at') &&
      (contains(fromJSON('["approved", "changes_requested"]'), github.event.review.state)) &&
      (contains(github.event.pull_request.labels.*.name , 'attn:pr-reviewers'))
    steps:
      - name: Full Context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"

      - uses: actions/github-script@v6
        with:
          script: |
            try {
              await github.rest.issues.removeLabel({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                name: 'attn:pr-reviewerssssssssssssssssssss'
              })
            } catch (error) {
              console.error(error)
              if (error.status === 404) {
                console.log(
                  "Occasionally there could be a weird situation where the label is already removed when the action " +
                  "gets triggered."
                );
              } else {
                throw error;
              }
            }
