name: State Management

on:
  pull_request:
    types: [review_requested]

jobs:
  add-tag:
    runs-on: ubuntu-latest
    if: |
      (github.event.pull_request.user.login == 'BoweiZhang-at') &&
      (!contains(github.event.pull_request.labels.*.name , 'attn:pr-reviewers'))
    steps:
      - name: Full Context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: Tag removal
        run: gh pr ${{github.event.pull_request.number}} --remove-label 'attn:pr-reviewers' || true
