name: State Management

on:
  pull_request:
    types: [review_requested]

jobs:
  open-tag:
    runs-on: ubuntu-latest
    if: ${{!contains(github.event.pull_request.labels.*.name , "attn:pr-reviewers")}}
    permissions:
      pull-requests: write
    steps:
      - name: Full Context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: WTF
        run: |
          echo 'wtf'
          echo ${{ !contains(github.event.pull_request.labels.*.name , "attn:pr-reviewers")}}
          echo ${{ github.event.pull_request.labels}}

      - uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ["attn:pr-reviewers"]
            })
