name: Remove label

on:
  pull_request_review:
    types: [submitted]

jobs:
  full-context:
    runs-on: ubuntu-latest
    steps:
      - name: Full Context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"

  remove-label:
    runs-on: ubuntu-latest
    if: |
      (github.event.pull_request.user.login == 'BoweiZhang-at') &&
      (contains(fromJSON('["approved", "changes_requested"]'), github.event.review.state)) &&
      (contains(github.event.pull_request.labels.*.name , 'attn:pr-reviewers'))
    steps:
      - name: Full Context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: Tag removal
        run: gh pr edit ${{github.event.pull_request.number}} --remove-label 'attn:pr-reviewers' || true
